package com.workerrobotics.rcljava.ffi;

import java.util.List;

/**
 * Convenience indirection to keep the rest of rcljava decoupled from the exact package names
 * generated by jextract.
 *
 * Your bindings artifact appears to expose an entrypoint class named `RclLib`.
 * Because the exact package can differ depending on generation settings, this class tries a few candidates.
 *
 * Update {@link #CANDIDATES} once you confirm the actual fully-qualified class name.
 */
public final class Bindings {
  private Bindings() {}

  /**
   * Candidate fully-qualified names for the generated entrypoint class.
   * Add/remove entries to match your generator output.
   */
  public static final List<String> CANDIDATES = List.of(
      "RclLib",
      "rcl.RclLib",
      "ros2.RclLib",
      "org.ros2.rcl.RclLib",
      "com.github.WorkerRobotics.RclLib",
      "com.github.workerrobotics.RclLib",
      "com.github.workerrobotics.ros2.RclLib",
      "com.github.WorkerRobotics.ros2.RclLib"
  );

  private static volatile Class<?> cachedRclLib;

  /** Resolve and cache the RclLib class. */
  public static Class<?> rclLibClass() {
    Class<?> c = cachedRclLib;
    if (c != null) return c;

    synchronized (Bindings.class) {
      if (cachedRclLib != null) return cachedRclLib;

      for (String name : CANDIDATES) {
        try {
          cachedRclLib = Class.forName(name);
          return cachedRclLib;
        } catch (ClassNotFoundException ignored) {
          // keep trying
        }
      }

      throw new IllegalStateException(
          "Could not find generated bindings entrypoint class 'RclLib' on the classpath.\n" +
          "Tried: " + CANDIDATES + "\n" +
          "Fix: update com.workerrobotics.rcljava.ffi.Bindings.CANDIDATES to include the correct FQCN."
      );
    }
  }

  /** Fail-fast check used by rcljava before attempting native calls. */
  public static void assertPresent() {
    rclLibClass(); // will throw with a good message if missing
  }
}
